site_name: University of Vocaloid China
site_url: https://wiki.feixilu.top
repo_url: https://github.com/wingtings/University-of-Vocaloid-China

theme:
  name: 'material'
  logo: img/中术大学.png
  favicon: img/favicon.svg
  features:
    - announce.dismiss
    - header.autohide
  palette:
    - primary: light blue
      # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

      # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
    - Home: index.md
    - 观影会活动:
        - 2024/10: 1.md
        - 2024/11: 2.md
        - 2024/12: 3.md
    - 中V推歌稿:
        - 2024/10: 1.md
        - 2024/11: 2.md
        - 2024/12: 3.md
    - 日V推歌稿:
        - 2024/10: 1.md
        - 2024/11: 2.md
        - 2024/12: 3.md
    - VC Pedia: https://vcpedia.cn/