site_name: University of Vocaloid China
site_url: https://wiki.feixilu.top
repo_url: https://github.com/wingtings/University-of-Vocaloid-China
copyright: Copyright @ University of Vocaloid China 2025

theme:
  name: 'material'
  custom_dir: docs/overrides
  logo: img/中术大学.png
  favicon: img/favicon.svg
  features:
    - announce.dismiss
    - header.autohide
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - navigation.footer
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按
    - content.tooltips

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 关闭自动模式
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: light blue # 上方的
      accent: indigo # 链接等可交互元件的高亮色
      toggle:
        icon: material/toggle-switch # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: indigo
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至日间模式

nav:
    - Home: index.md
    - 产出作品:
        - 原创歌曲: ./Works/原创歌曲.md
        - 翻调作品: ./Works/翻调作品.md
        - PV/绘画作品: ./Works/PV绘画作品.md
        - 宣传海报: ./Works/宣传海报.md
    - 调校活动:
        - 2024 Fall:
            - 迭羽P的开课尝试: ./Synthesis/2024_Fall/迭羽P的开课尝试.md
            - 2025寒假“依言依语”活动: ./Synthesis/2024_Fall/2025寒假“依言依语”活动.md
        - 2025 Spring:
            - 乐正绫十周年“拾光忆绫”活动: ./Synthesis/2025_Spring/乐正绫十周年“拾光忆绫”活动.md
        - 2025 Fall:
            - 调校周常: ./Synthesis/2025_Fall/调校周常.md
    - 大型演出活动:
        - 2025 Spring:
            - 中国科大ACG音乐会: ./Stages/2025_Spring/中国科大ACG音乐会.md
    - 观影会活动:
        - 2024 Fall:
            - 2024洛天依无线共鸣演唱会: ./Movies/2024_Fall/2024洛天依无线共鸣演唱会.md
        - 2025 Spring:
            - 乐正绫十周年生日会: ./Movies/2025_Spring/乐正绫十周年生日会.md
        - 2025 Fall:
            - 2025洛天依无限共鸣演唱会: ./Movies/2025_Fall/2025洛天依无限共鸣演唱会.md
    - 中V推歌:
        - 2024 Fall:
            - 1st.「世末歌者」: ./Chinese_Songs/2024_Fall/1st.「世末歌者」.md
            - 2nd.「大概是关于勇者战胜某个魔王的王道故事⁉️」: ./Chinese_Songs/2024_Fall/2nd.「大概是关于勇者战胜某个魔王的王道故事⁉️」.md
            - 3rd.「纯蓝」: ./Chinese_Songs/2024_Fall/3rd.「纯蓝」.md
            - 4th.「白鸟过河滩」: ./Chinese_Songs/2024_Fall/4th.「白鸟过河滩」.md
            - 2025寒假短篇特辑: ./Chinese_Songs/2024_Fall/2025寒假短篇特辑.md
        - 2025 Spring:
            - 6th.「相思若循」: ./Chinese_Songs/2025_Spring/6th.「相思若循」.md
            - 8th.「三月雨」: ./Chinese_Songs/2025_Spring/8th.「三月雨」.md
            - 9th.「深夜诗人」: ./Chinese_Songs/2025_Spring/9th.「深夜诗人」.md
            - 10th.「星火燎原」: ./Chinese_Songs/2025_Spring/10th.「星火燎原」.md
            - 11th.「反乌托邦」: ./Chinese_Songs/2025_Spring/11th.「反乌托邦」.md
            - 12th.「宿命论」: ./Chinese_Songs/2025_Spring/12th.「宿命论」.md
            - 13th.「青春追梦人」: ./Chinese_Songs/2025_Spring/13th.「青春追梦人」.md
        - 2025 Fall:
            - 14th.「文学少女的忧郁」: ./Chinese_Songs/2025_Fall/14th.「文学少女的忧郁」.md
            - 15th.「天行健」: ./Chinese_Songs/2025_Fall/15th.「天行健」.md
    - 日V推歌:
        - 2024 Fall:
            - 长推 I.「命に嫌われている(被生命所厌恶)」: ./Japanese_Songs/2024_Fall/-24autumn 长推 I.「命に嫌われている(被生命所厌恶)」.md
            - 长推 II.「もうじき夏が終わるから(因为夏夜将终)」: ./Japanese_Songs/2024_Fall/-24autumn 长推 II.「もうじき夏が終わるから(因为夏夜将终)」.md
            - 长推 III.「メルト（Melt 融化）」: ./Japanese_Songs/2024_Fall/-24autumn 长推 II.「もうじき夏が終わるから(因为夏夜将终)」.md
            - 长推 IV.「SnowMix♪」: ./Japanese_Songs/2024_Fall/-24autumn 长推 IV.「SnowMix♪」.md
            - 24winter 短推 I-「那些喧嚣或静谧的节日时光里」: ./Japanese_Songs/2024_Fall/-24winter 短推 I-「那些喧嚣或静谧的节日时光里」.md
        - 2025 Spring:
            - 短推 I-「熙熙攘攘、我们回转向前——」: ./Japanese_Songs/2025_Spring/-25spring 短推 I-「熙熙攘攘、我们回转向前——」.md
            - 短推 II-「wowaka-将零落的情绪编织成心灵」: ./Japanese_Songs/2025_Spring/-25spring 短推 II-「wowaka-将零落的情绪编织成心灵」.md
            - 短推 III-「独身一人的少年少女们」: ./Japanese_Songs/2025_Spring/-25spring 短推 III-「独身一人的少年少女们」.md
            - 短推 III-特辑「オノマトペメガネ」: ./Japanese_Songs/2025_Spring/-25spring 短推 III-特辑「オノマトペメガネ」.md
            - 短推 IV-「致那翱翔天空的遥远的梦」: ./Japanese_Songs/2025_Spring/-25spring 短推 IV-「致那翱翔天空的遥远的梦」.md
        - 2025 Fall:
            - 短推 I-「始まりの風は吹いているよ」: ./Japanese_Songs/2025_Fall/-25autumn 短推 I-「始まりの風は吹いているよ」.md
    - 其他:
        - 英v推歌: ./Others/English_Songs/111.md
        - 你社的一些名人名梗名事:
            - 乐正肥西路: ./Others/People/乐正肥西路.md
            - 桜舞Phymusics: ./Others/People/桜舞Phymusics.md
            - 立方体: ./Others/People/立方体.md
            - YXAIN: ./Others/People/YXAIN.md
            - wingtings: ./Others/People/wingtings.md
    - 社团会议:
        - 2024 Fall:
            - 院级社团筹备以及建立: ./Meetings/2024_Fall/院级社团筹备以及建立.md
            - 社团大会: ./Meetings/2024_Fall/社团大会.md
            - 干事工作会: ./Meetings/2024_Fall/干事工作会.md
        - 2025 Spring:
            - 社团大会: ./Meetings/2025_Spring/社团大会.md
            - 干事工作会: ./Meetings/2025_Spring/干事工作会.md
        - 2025 Fall:
            - 校级社团筹备以及答辩: ./Meetings/2025_Fall/校级社团筹备以及答辩.md
            - 社团大会: ./Meetings/2025_Fall/社团大会.md
            - 干事工作会: ./Meetings/2025_Fall/干事工作会.md
    - VC Pedia: https://vcpedia.cn/

# Markdown extensions
markdown_extensions: #详见https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/ 和 https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  # - meta # 支持Markdown文件上方自定义标题标签等
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.arithmatex: # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  generator: false #是否删除页脚显示“使用 MkDocs 材料制造”
  social:
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/381317768
      name: social account on BiliBili

    - icon: fontawesome/brands/qq
      link: http://3986895738.qzone.qq.com
      name: social account on QQ

plugins:
  - search: #搜索配置
      lang: zh
  - tags
  - meta:
      meta_file: .meta.yml
  - document-dates:
      position: bottom         # 显示位置：top（标题后） bottom（文档末尾），默认：bottom
      type: date               # 时间类型：date datetime timeago，默认：date
      locale: zh               # 本地化语言：en zh zh_TW es fr de ar ja ko ru，默认：en
      date_format: '%Y-%m-%d'  # 日期格式化字符串，例如：%Y年%m月%d日、%b %d, %Y
      time_format: '%H:%M:%S'  # 时间格式化字符串（仅在 type=datetime 时有效）
      exclude: # 排除文件列表，默认为空
#        - temp.md              # 排除指定文件
#        - private/*            # 排除 private 目录下所有文件，包括子目录
      show_author: true        # 是否显示作者信息，默认：true