site_name: University-of-Vocaloid-China
site_url: https://wiki.feixilu.top
repo_url: https://github.com/wingtings/University-of-Vocaloid-China

theme:
  name: 'material'

nav:
    - Home: index.md
    - 观影会活动:
        - 2024/10: 1.md
        - 2024/11: 2.md
        - 2024/12: 3.md
    - 中V推歌稿:
        - 2024/10: 1.md
        - 2024/11: 2.md
        - 2024/12: 3.md
    - 日V推歌稿:
        - 2024/10: 1.md
        - 2024/11: 2.md
        - 2024/12: 3.md
    - VC Pedia: https://vcpedia.cn/